2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data/db 64-bit host=6e9f32535582
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten] db version v3.6.3
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten] git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten] modules: none
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten] build environment:
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-06-09T15:21:22.358+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "0.0.0.0", port: 27017 }, processManagement: { fork: true }, storage: { dbPath: "/data/db" }, systemLog: { destination: "file", path: "/data/logs" } }
2019-06-09T15:21:22.358+0000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
2019-06-09T15:21:22.359+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2019-06-09T15:21:22.359+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2019-06-09T15:21:22.359+0000 I STORAGE  [initandlisten] 
2019-06-09T15:21:22.359+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2019-06-09T15:21:22.359+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2019-06-09T15:21:22.359+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7454M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2019-06-09T15:21:23.257+0000 I STORAGE  [initandlisten] WiredTiger message [1560093683:257313][8:0x7f2e38c1ff80], txn-recover: Main recovery loop: starting at 20/27264
2019-06-09T15:21:23.257+0000 I STORAGE  [initandlisten] WiredTiger message [1560093683:257692][8:0x7f2e38c1ff80], txn-recover: Recovering log 20 through 21
2019-06-09T15:21:23.365+0000 I STORAGE  [initandlisten] WiredTiger message [1560093683:365280][8:0x7f2e38c1ff80], txn-recover: Recovering log 21 through 21
2019-06-09T15:21:23.869+0000 I CONTROL  [initandlisten] 
2019-06-09T15:21:23.869+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-06-09T15:21:23.869+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-06-09T15:21:23.870+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2019-06-09T15:21:23.870+0000 I CONTROL  [initandlisten] 
2019-06-09T15:21:23.918+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2019-06-09T15:21:23.918+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2019-06-09T15:21:24.004+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2019-06-09T15:21:42.691+0000 I NETWORK  [listener] connection accepted from 172.18.0.1:40596 #1 (1 connection now open)
2019-06-09T15:21:42.692+0000 I NETWORK  [conn1] received client metadata from 172.18.0.1:40596 conn: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.18.0-21-generic" }, platform: "CPython 3.6.7.final.0" }
2019-06-09T15:21:43.244+0000 I NETWORK  [conn1] end connection 172.18.0.1:40596 (0 connections now open)
